[components]
include = [
  "astronverse-ai",
  "astronverse-browser",
  "astronverse-cua",
  "astronverse-dataprocess",
  "astronverse-datatable",
  "astronverse-dialog",
  "astronverse-email",
  "astronverse-encrypt",
  "astronverse-enterprise",
  "astronverse-excel",
  "astronverse-input",
  "astronverse-network",
  "astronverse-openapi",
  "astronverse-pdf",
  "astronverse-report",
  "astronverse-script",
  "astronverse-smart",
  "astronverse-software",
  "astronverse-system",
  "astronverse-verifycode",
  "astronverse-vision",
  "astronverse-window",
  "astronverse-winelement",
  "astronverse-word",
]
