atomic:
  Hello.print:
    title: Hello打印
    comment: Hello打印
    icon: ''
    helpManual: ''
    inputList:
    - key: print_type
      title: 打印类型
      tip: ''
    - key: print_msg
      title: 打印内容
      tip: ''
    outputList:
    - key: msg
      title: 日志
      tip: ''
options:
  ReportLevelType:
  - value: info
    label: 信息
  - value: warning
    label: 警告
  - value: error
    label: 错误
